from locations import room1,room2

table = {
    ((room1,'empty'),): 'MoveRight',
    ((room1,'MilkHere'),): 'Drink',
    ((room1,'SausageHere'),): 'Eat',
    ((room2,'empty'),): 'MoveLeft',
    ((room2,'MilkHere'),): 'Drink',
    ((room2,'SausageHere'),): 'Eat',
    ((room1,'empty'),(room2,'MilkHere')):'Drink',
    ((room1,'empty'),(room2,'SausageHere')):'Eat',
    ((room1,'empty'),(room2,'empty')):'MoveLeft',
    ((room1,'MilkHere'),(room1,'empty')):'MoveRight',
    ((room1,'SausageHere'),(room1,'empty')):'MoveRight',
    ((room2,'empty'),(room1,'empty')):'MoveRight',
    ((room2,'empty'),(room1,'MilkHere')):'Drink',
    ((room2,'empty'),(room1,'SausageHere')):'Eat',
    ((room2,'MilkHere'),(room2,'empty')):'MoveLeft',
    ((room2,'SausageHere'),(room2,'empty')):'MoveLeft',
    ((room1,'empty'),(room2,'MilkHere'),(room2,'empty')):'MoveLeft',
    ((room1,'empty'),(room2,'SausageHere'),(room2,'empty')):'MoveLeft',
    ((room1,'empty'),(room2,'empty'),(room1,'empty')):'MoveRight',
    ((room1,'MilkHere'),(room1,'empty'),(room2,'empty')):'MoveLeft',
    ((room1,'MilkHere'),(room1,'empty'),(room2,'MilkHere')):'Drink',
    ((room1,'MilkHere'),(room1,'empty'),(room2,'SausageHere')):'Eat',
    ((room1,'SausageHere'),(room1,'empty'),(room2,'empty')):'MoveLeft',
    ((room1,'SausageHere'),(room1,'empty'),(room2,'MilkHere')):'Drink',
    ((room1,'SausageHere'),(room1,'empty'),(room2,'SausageHere')):'Eat',
    ((room2,'empty'),(room1,'empty'),(room2,'empty')):'MoveLeft',
    ((room2,'empty'),(room1,'MilkHere'),(room1,'empty')):'MoveRight',
    ((room2,'empty'),(room1,'SausageHere'),(room1,'empty')):'MoveRight',
    ((room2,'MilkHere'),(room2,'empty'),(room1,'empty')):'MoveRight',
    ((room2,'MilkHere'),(room2,'empty'),(room1,'MilkHere')):'Drink',
    ((room2,'MilkHere'),(room2,'empty'),(room1,'SausageHere')):'Eat',
    ((room2,'SausageHere'),(room2,'empty'),(room1,'empty')):'MoveRight',
    ((room2,'SausageHere'),(room2,'empty'),(room1,'MilkHere')):'Drink',
    ((room2,'SausageHere'),(room2,'empty'),(room1,'SausageHere')):'Eat',
}
